enableGlobalCache: true

nodeLinker: node-modules

progressBarStyle: default

supportedArchitectures:
  cpu:
    - x86_64
    - arm64
    - arm
  os:
    - linux
    - linux-arm
    - darwin

yarnPath: .yarn/releases/yarn-3.6.3.cjs
