compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

progressBarStyle: default

supportedArchitectures:
  cpu:
    - x86_64
    - arm64
    - arm
    - x64
  os:
    - linux
    - linux-arm
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.0.2.cjs
